username:
password:
phone_number: 

profile_path: '' # Can be empty, will default to system Chrome profile path
chrome_profile_name: 'Default' # Specific Chrome profile to use for this candidate

role_type: ML # Options: ML, UI, QA

positions:
- ML Engineer 
- Gen AI Engineer
- LLM Engineer

locations:
# - Bay Area, CA
# - USA, Remote
- Delhi


roletype:
- 1 # onsite
- 2 # remote
- 3 # hybrid

salary: 150,000
rate: 75

uploads:
  Resume: resumes/sample_resume.pdf
 

gender: Male 

output_filename:
- output/applications/applications.csv

blacklist:
- Workday
- Company Name 1
- Company Name 2